### PR TITLE
[WIP] Validation:Updates in SAS

### PR DESCRIPTION
**Pull request by GoFroggyRun**
This PR deals with the changes that have been made recently in the SAS calculator.

### CODE REVIEW

**Comment by martinholmer** [comment]
@GoFroggyRun,  This is an impressive amount of cross-model validation work!  My only question is this: do you see this as the end of your work?  Or, at least, a milestone in your work that could be committed to the master branch before you continue further work?  Or, are you going to be making more commits to this pull request in the next few days?

**Comment by GoFroggyRun** [comment]
@martinholmer, Hi. I'm planning to feed two calculators with 09 PUF under 2013 logic shortly for further verification. And it's kinda hard to decide whether I'm confident about this version at this moment. However, you could expect an update from me sometime tomorrow, after another round of validation.

**Comment by MattHJensen** [comment]
@martinholmer, a bit more context here: 

@GoFroggyRun was testing both calculators with 2008 data. Updating this repo to the 2009 puf means that he needs to use the 2009 puf with SAS as well, which he is in the middle of. 

Thus far he has been more careful with (and is receiving review from @feenberg on) changes to the SAS code. Changes to the python code implicitly have @feenberg's review because they are being made to match the SAS code, but @GoFroggyRun (and @Amy-Xu and me) will want to review them more closely against the forms just to be sure before we start merging anything.  

However, once @GoFroggyRun reports that the WIP PR to the SAS repo and this WIP PR to this Python repo are matching with the 2009 PUF being run on 2013 data, then I think it would make sense for you to start testing this PR against internet TAXSIM.  That way if you find differences between this PR and internet TAXSIM, we will know reflexively that those differences also exist between the SAS repo and internet TAXSIM.

**Comment by martinholmer** [comment]
@MattHJensen,  Thanks for the context on the SAS-vs-taxcalc cross-checking project.

It sounds as if its going to be a couple of days, at the least, before the pull request can be tested with the validation tools I'm developing.  I'll wait for your signal.

But meanwhile, perhaps I should prepare a pull request with a simple change to the Records class constructor.  On the master branch now, the logic at the end of the constructor below the comment that says "Imputations" seems like it makes sense to execute __only__ if the input data are for 2009.   Here is the ctor code:
```
def __init__(self,
                 data="puf.csv",
                 blowup_factors=blowup_factors_path,
                 weights=weights_path,
                 start_year=None,
                 **kwargs):

        self.read(data)
        self.read_blowup(blowup_factors)
        self.read_weights(weights)
        if (start_year):
            self._current_year = start_year
        else:
            self._current_year = self.FLPDYR[0]

        """Imputations"""
        self._cmbtp_itemizer = None
        self._cmbtp_standard = self.e62100 - self.e00100 + self.e00700
        self.mutate_imputations()  # Updates the self._cmbtp_itemizer variable

        # Standard deduction amount in 2009
        std2009 = np.array([5700, 11400, 5700, 8350, 11400, 5700, 950])
        # Additional standard deduction for aged 2009
        STD_Aged_2009 = np.array([1400., 1100.])
        # Compulsory itemizers
        self._compitem = np.where(np.logical_and(self.FDED == 1,
                                                 self.e04470 <
                                                 std2009[self.MARS - 1]), 1, 0)
        # Number of taxpayers
        self._txpyers = np.where(np.logical_or(self.MARS == 2,
                                               np.logical_or(self.MARS == 3,
                                                             self.MARS == 6)),
                                 2., 1.)
        # Number of extra standard deductions for aged
        self._numextra = np.where(np.logical_and(self.FDED == 2, self.e04470 <
                                  std2009[self.MARS - 1]),
                                  np.where(
                                  np.logical_and(self.MARS != 2,
                                                 self.MARS != 3),
                                  (self.e04470 - std2009[self.MARS - 1]) /
                                  STD_Aged_2009[0],
                                  (self.e04470 - std2009[self.MARS - 1]) /
                                  STD_Aged_2009[1]),
                                  np.where(self.e02400 > 0, self._txpyers, 0))
        self._puf_year = 2009
```
So, the pull request I could prepare would simply add an ```if self._current_year == 2009:``` guard for the imputation logic.  Does this make sense?  Or am I missing something?

**Comment by GoFroggyRun** [comment]
The python calculator should be almost surely the same as SAS calculator in terms of 2013 tax logic at this moment. There are some minor bug in the SAS calc to be fixed shortly.

**Comment by MattHJensen** [comment]
Excellent @GoFroggyRun: Does this mean that once you bring this PR up to date with master, then any differences @martinholmer might find between this PR and taxsim are also differences between SAS taxcalc and taxsim? If so, I would view it as a good opportunity for @martinholmer to start his taxsim testing. 

Also, have you checked each of these changes against the tax forms yet, or is that the next step? If it is the next step, could you provide a citation of the appropriate tax form that you checked for each change and leave comments similar to those that you left on the SAS repo?  If you find that you have made any changes that the tax forms don't justify, then we should reverse the change here as well as modify the SAS repo.

**Comment by feenberg** [comment]
On Thu, 1 Oct 2015, Matt Jensen wrote:

> 
> Excellent @GoFroggyRun: Does this mean that once you bring this PR up to date with
> master, then any differences @martinholmer might find between this PR and taxsim are
> also differences between SAS taxcalc and taxsim? If so, I would view it as a good
> opportunity for @martinholmer to start his taxsim testing.


I just created the taxsim format data from the 2009 PUF this morning and 
want to write a program to compare taxcalc-sas with taxsim before sending 
Martin the taxsim values. It will be easier for me to do this since I have 
familiarity with both programs.

Once I have looked at the differences, Martin should compare to python 
results. This weekend should give me the time to write the program and 
make the runs.

dan

**Comment by GoFroggyRun** [comment]
@MattHJensen  Regarding your second question, some of the changes have been verified while some are not. So I think the next step would be put the existing citations as well as find reference for those remaining updates.

**Comment by MattHJensen** [comment]
> @MattHJensen Regarding your second question, some of the changes have been verified while some are not. 

Thanks for the clarification @GoFroggyRun. 

>So I think the next step would be put the existing citations as well as find reference for those remaining updates.

Could you fix conflicts with master before doing the citations? That would make this more helpful for @martinholmer

**Comment by GoFroggyRun** [comment]
@MattHJensen OK Will do.

**Comment by MattHJensen** [comment]
> I just created the taxsim format data from the 2009 PUF this morning and
want to write a program to compare taxcalc-sas with taxsim before sending
Martin the taxsim values. It will be easier for me to do this since I have
familiarity with both programs.

Thank you @feenberg, this will be very helpful. As an aside, do full taxsim and internet taxsim produce the same results from the same 22-var input?

**Comment by feenberg** [comment]
On Thu, 1 Oct 2015, Matt Jensen wrote:

>
>       I just created the taxsim format data from the 2009 PUF this
>       morning and
>       want to write a program to compare taxcalc-sas with taxsim
>       before sending
>       Martin the taxsim values. It will be easier for me to do this
>       since I have
>       familiarity with both programs.
> 
> Thank you @feenberg, this will be very helpful. As an aside, do full taxsim
> and internet taxsim produce the same results from the same 22-var input?

The 22 variable version puts each variable in one of the variable slots in 
the larger model. But none of the 22 variables allow education credits to 
be estimated, so the result of condensing 200 variables in to 22 will 
cause some differences. If the question is about taking 22 variables and 
giving them to the larger model, that shouldn't ever see any difference.

dan

**Pull request closed without merging**
