### PR TITLE
Fix bug in NIIT

### PR DESCRIPTION
**Pull request by MattHJensen**
We currently have a bug that causes us to get different results under the two scenarios below:

1. load a calculator, increment year, and calculate taxes 
2. load a calculator, calculate taxes, increment year, and then calculate taxes again. 

This corresponds to Scenario 1 and Scenario 2 of issue #203. 

I have identified the net investment income tax (NIIT) as the source of this bug. 

NIIT is currently reassigned if AGI is greater than the NIIT threshold: 

    if c00100 > NIIT_thd[MARS - 1]:
        NIIT  = NIIT_trt * min(e00300 + e00600 + max(0, c01000)
                + max(0, e02000), c00100 - NIIT_thd[MARS - 1])

This means that if we calculate taxes, increment year, and calculate taxes again, something like this could happen to a record: In the first year, AGI is greater than the NIIT threshold, so NIIT is assigned to a non-zero value. In the second year, AGI is less than the NIIT threshold, so NIIT is neither reassigned nor is it zero-- rather it would be the value that it was assigned in the first year. This is a bug.

I fixed this problem by adding an else statement that explicitly assigns NIIT to zero if it does not pass the if condition:

    if c00100 > NIIT_thd[MARS - 1]:
        NIIT  = NIIT_trt * min(e00300 + e00600 + max(0, c01000)
                + max(0, e02000), c00100 - NIIT_thd[MARS - 1])
    else: NIIT = 0
    return NIIT

Alternatively, I could have replaced all of that with: 
        
    NIIT  = max(0, NIIT_trt * min(e00300 + e00600 + max(0, c01000)
                + max(0, e02000), c00100 - NIIT_thd[MARS - 1]))

One question is whether we should be worried about this type of problem occurring again in the future. We could, for instance, re-zero all of the `zeroed_names` from records.py as a part of increment_year().

### CODE REVIEW

**Comment by feenberg** [comment]
I have found it helpful to zero everything in both the fortran and SAS versions of my calculator.

**Comment by MattHJensen** [comment]
FYI, I just reworded the description of the bug in the first comment. It should be clearer now.

**Comment by MattHJensen** [comment]
Note that this bugfix only slightly affects our diagnostics table since the bug is so small and we round everything off. 

###### BEFORE (branch master)
image



###### AFTER (branch issue203)
image

**Comment by MattHJensen** [comment]
Fixed with 0b24eba. Continuing discussion of how to avoid bugs like this in the future with #272. Closing.

**Pull request merged**
