### PR TITLE
Make SimpleTaxIO use new e00200p and e00200s Records variables

### PR DESCRIPTION
**Pull request by martinholmer**

### CODE REVIEW

**Comment by martinholmer** [comment]
@MattHJensen and @talumbau,
Why do I get this error from Travis-CI in pull request #390 when on my computer test_3 in test_simpletaxio.py passes without any problems?

**Comment by talumbau** [comment]
hmm... just looked at the error. I am using numba v0.21.0 and numpy v.1.9.3, which is what Travis CI is using for this build, so I don't think that should be an issue. What platform are you developing on? Mac/Windows/Linux?

**Comment by martinholmer** [comment]
Mac

**Comment by talumbau** [comment]
OK, I can try to duplicate the error and get it to fail for me. I have a Linux 64-bit VM so if it is a platform specific thing that will hopefully reproduce it.

**Comment by martinholmer** [comment]
@talumbau,  Thanks for looking into the Travis-CI problem I'm having.  This pull request has been merged into the master branch with the Travis-CI-error-causing statement (in test_simpletaxio.py test_3) comment out.  Not having a complete test_3 has aleady caused problems: somebody made changes to Records class that broke the SimpleTaxIO class.  This would have been caught before the merge if test_3 had been complete.  So, I am eager to know what you find in your testing.

**Pull request merged**
