### PR TITLE
Corrections to AMTI calculations

### PR DESCRIPTION
**Pull request by mmessick**
This PR deals with issue #300

### CODE REVIEW

**Comment by mmessick** [comment]
current master:
image

this pr:
screen shot 2015-07-09 at 3 05 57 pm

**Comment by talumbau** [comment]
I would recommend merging master into this branch and then update the PR (by pushing to mmessick:correctionsToCalculation). this will update the table and allow travis CI to run

**Comment by mmessick** [comment]
Doesn't look like there are any major changes. Will look into smaller changes

current master:
image

pr table:
screen shot 2015-07-09 at 3 44 12 pm

**Comment by mmessick** [comment]
diagnostic table for new calculation of c62100 (Alternative Minimum Taxable Income):
screen shot 2015-07-09 at 4 46 44 pm


The only changes occur for the three AMT rows. Not huge changes, but noticeable increases in values across the columns.

**Comment by mmessick** [comment]
@Amy-Xu, can you review this when you get a chance? Thanks.

**Comment by MattHJensen** [comment]
@mmessick Sorry to make you do this, but could you merge master and then post the pr and master tables again? I just merged Amy's pr, which changed the basleine considerably.

**Comment by mmessick** [comment]
new master:
screen shot 2015-07-09 at 5 02 47 pm

new pr:
screen shot 2015-07-09 at 5 06 07 pm


Like before, the only changes occur for the three AMT rows. Not huge changes, but noticeable increases in values across the columns.

**Comment by mmessick** [comment]
@MattHJensen, I think I have the right master table now. Looking at the two in comparison, the only differences are the AMT rows which are all noticeably higher values than before.

**Comment by MattHJensen** [comment]
#301 was the last PR merged. I'm surprised the "master" table of this pr doesn't match the "pr" table from #301.

**Comment by MattHJensen** [comment]
Ahh, I'm sorry. I was looking at the wrong table. Please disregard the previous comment.

**Comment by mmessick** [comment]
also deals with issue #303

**Comment by mmessick** [comment]
final distribution table for this pr:
screen shot 2015-07-10 at 2 47 40 pm

@Amy-Xu, can you approve this?

**Comment by Amy-Xu** [comment]
AMT's changing in the direction expected. So far the table looks good to me.

**Comment by mmessick** [comment]
The changes the PR has:
1) issue #300
currently we calculate c60130 like this:

    c60130 = c21040 + x60130

proposed change (from instructions for Form 6251):

    if c00100 >  ID_ps[MARS-1]:
        c60130 = -(e18300)
    else:
        c60130 = 0

2) issue #303 
original calculation for c62100. when puf == True and ((_standard == 0 or (_exact == 1 and e04470 > 0)):

    c62100 = (c00100 - c04470 + min(c17000, 0.025 * max(0., c00100)) + 
            (1-ID_StateLocalTax_HC)*_sit + e18500 - c60260 + c20800 - c21040 )

proposed change:

    c62100 = (c00100 - c04470 + max(0., min(c17000, 0.025 * c00100)) +
                 (1-ID_StateLocalTax_HC)*_sit + c60240 - c60260 + c20800
                  - c21040 + c60130)

@feenberg, could you please review these changes? thanks so much!

**Comment by MattHJensen** [comment]
@mmessick could you give an update on the status of this PR? I see that the motivating issue (#300) has been closed already.

**Comment by mmessick** [comment]
@MattHJensen, yes issue #300 has been closed due to comments from @feenberg, however, the second issue (#303), is still open and up for discussion. @Amy-Xu and I both agree with the proposed changes outlines in the last comment there, but would also like review on it before this PR gets reviewed or merged

**Comment by MattHJensen** [comment]
@GoFroggyRun could you decide what to do with this PR as part of your testing work? In particular see the last comment on issue #303, which is relevant to this PR. It might be cleaner to close this PR and incorporate any change in the PRs that come out of your testing. Alternatively, you could review this and if it looks good @mmessick could resolve conflicts and then we could merge this and you could check out the latest version of master with these changes included for your testing.

**Comment by GoFroggyRun** [comment]
@MattHJensen sure, I'll take a look.

**Comment by GoFroggyRun** [comment]
@MattHJensen @mmessick 's proposal regarding #303 makes sense to me in the way that it is more compatible with what's on the tax form. However, at this moment, I might leave c62100 unchanged. I'll incorporate the proposal while running the validation based on 09 PUF to see its effect.

**Comment by MattHJensen** [comment]
@GoFroggyRun, should I close this PR?

**Comment by GoFroggyRun** [comment]
@MattHJensen One moment, the thing is changing from 
`min(c17000, 0.025 * max(0., c00100))`     to     `max(0., min(c17000, 0.025 * c00100))`
makes a lot of sense. But the rest of the changes look a little bit suspicious and yield huge difference. I'd like to investigate a bit more before closing this PR.

**Comment by GoFroggyRun** [comment]
@MattHJensen So I'll use
`max(0., min(c17000, 0.025 * c00100))` instead of `min(c17000, 0.025 * max(0., c00100))` in the calculation, which yields exactly the same results but corresponds better to the tax form. 
However, replacing `+ e18500` by `+ c60240 + c60130` shall not be correct. In particular, 
`c60130 = c21040 + x60130 = c21040`, 
and 
`c60240 = (1 - ID_StateLocalTax_HC) * c18300 + x60240 = c18300`. 
The first part, `c60130`, cancels `c21040` and the second part, `c60240`, already includes `_statax` or `_sit`. As a result, please close this PR. Thanks!

**Comment by MattHJensen** [comment]
Ok, @GoFroggyRun, merging. Thank you @mmessick!

**Pull request closed without merging**
