### PR TITLE
Education credit changes

### PR DESCRIPTION
**Pull request by xiyuw123**
Added 3 lines of code to NonEdCr that should calculate the amount of nonrefundable education credits

### CODE REVIEW

**Comment by MattHJensen** [comment]
Could you open a corresponding issue, with the "tax" and "bug" labels where you describe the problem in the current code? Then you can link to that issue from this PR.

**Comment by xiyuw123** [comment]
Hi Matt, I just opened an issue for the education credits. I don't have permission to add labels though. Here it is: https://github.com/OpenSourcePolicyCenter/Tax-Calculator/issues/218

**Comment by MattHJensen** [comment]
@xiyuw123, could show the diagnostic table before and after this change?

**Comment by xiyuw123** [comment]
Sure. This is the original master output:
ospc master output

This is the output after the education credits change:
ospc education credits

**Comment by MattHJensen** [comment]
Did you expect both refundable and nonrefundable credits to change?

**Comment by xiyuw123** [comment]
Only nonrefundable credits should have changed. I'm not sure at the moment why the nonrefundable credits change also.

**Comment by xiyuw123** [comment]
So the education credits also seem to change for the 2011 calculations, the one that was originally included in the SAS code.

2011 with the code for education credits commented out:
ospc 2011 output no educr changes

2011 with the code left in:
ospc education credits

**Comment by MattHJensen** [comment]
Looks like the second table is for 2013 instead of 2011.

**Comment by xiyuw123** [comment]
Sorry about that; I posted the wrong picture! It should be fixed now.

**Comment by MattHJensen** [comment]
Thanks! It seems like you should keep digging into the link in our code between the education credit and other refundable credits.

**Comment by xiyuw123** [comment]
So the reason the nonrefundable credits change is because the education credits are used in the calculations for the child tax credit. A higher education credit decreases the amount of the child tax credit. The child tax credit is then used in the (refundable) additional child tax credit, which will increase if the child tax credit decreases. As a result, the refundable credits also increase. The additional child tax credit is pretty much the only refundable credit affected by the education credit.

**Comment by MattHJensen** [comment]
Opps, looks like this got merged in as a part of #220. @xiyuw123, could you open an issue that describes the fact that you're still figuring out the interaction between the nonrefundable education credit and the refundable ACTC?

**Comment by xiyuw123** [comment]
Yep, sure. I've been looking through the forms for the child tax credit and the ACTC and it seems like that's what supposed to happen, but here is the issue: https://github.com/OpenSourcePolicyCenter/Tax-Calculator/issues/239

**Pull request merged**
