### PR TITLE
calc/apply beyond taxgains - vanilla

### PR DESCRIPTION
**Pull request by MattHJensen**
This is a vanilla-python implementation of the calc/apply style for the functions beyond taxgains. It still needs to be massaged to work well with jit (i.e., I haven't ensured that variable types are static).

### CODE REVIEW

**Comment by jlyons871** [comment]
@MattHJensen, have you tested this on the full puf file? I get different results compared to the master when I run test.py

**Comment by MattHJensen** [comment]
Is it expected that this fails the tests?

**Comment by talumbau** [comment]
No it is not expected. We will need to track this down.

**Comment by talumbau** [comment]
Looks like a Python 3 error according to Travis CI. @jlyons871, can you reproduce?

**Comment by jlyons871** [comment]
It works in both Python 2 and 3 on my mac but I can reproduce on windows. I am looking into it.

**Comment by talumbau** [comment]
I can reproduce with Python 3 on Mac. Weird.

**Pull request merged**
