### PR TITLE
[WIP]validation_SAS

### PR DESCRIPTION
**Pull request by GoFroggyRun**

### CODE REVIEW

**Comment by GoFroggyRun** [comment]
Most changes haven't been verified and py.test won't pass

**Comment by MattHJensen** [comment]
@GoFroggyRun looks like you might not be current with master.

**Comment by martinholmer** [comment]
@MattHJensen is correct.  You are working with a branch that has not been synchronized with the master branch for at least ten days, so you are missing all the enhancements in pull request #343 among other things.

**Comment by GoFroggyRun** [comment]
@MattHJensen  @martinholmer, this branch has actually been synchronized with the master a couple days ago, but the three files that I have been working on are not. I'll fix the issues and open a new PR.

**Comment by GoFroggyRun** [comment]
Error, please ignore.

**Pull request closed without merging**
