### PR TITLE
Parameterized capital gain section for both AMT and regular tax

### PR DESCRIPTION
**Pull request by Amy-Xu**
In this PR, 

- Capital gains for AMT and regular taxes are using different parameters, but the same default values.
- Both tax rates and thresholds are parameterized 

The parameter names used in this PR are in line with the latest webapp layout spreadsheet.

@MattHJensen Could you review the changes?

Before:
screen shot 2015-04-13 at 3 31 01 pm

After:
screen shot 2015-04-13 at 3 29 48 pm

### CODE REVIEW

**Comment by MattHJensen** [comment]
@Amy-Xu could you check out why there are some minor output changes?

**Comment by Amy-Xu** [comment]
The parameters weren't inflated before. This is the table after making the thresholds parameters inflated.
screen shot 2015-04-14 at 1 20 49 pm

**Comment by MattHJensen** [comment]
The code looks good to me. Could you do another test before we merge, though, which is to increase all of the rates under master by a point and increase all of the rates under the new version by a point and make sure we get the same thing?

**Comment by Amy-Xu** [comment]
Master: increased cgrate1 and cgrate1 by 0.01 and manually increase cap gain rates for regular tax by 0.01
screen shot 2015-04-14 at 2 58 54 pm

PR branch: increased all six parameter rate by 0.01
screen shot 2015-04-14 at 2 55 22 pm

**Comment by MattHJensen** [comment]
Great. Thanks @Amy-Xu. Merging.

**Pull request merged**
