### PR TITLE
Revise functions.py to eliminate differences with Internet TAXSIM

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request makes two changes in functions.py in order to eliminate all significant differences in total income tax liability in the 2013 and 2014 samples of filing units with no itemized-deduction expenses and no child-care expenses.

Before these two functions.py changes the tax differences were as follows:
```
taxcalc/validation> cat a13.taxdiffs
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 19    209    209     -0.01 [36]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 22   1353      0    -25.00 [46]
     #big_vardiffs_with_big_inctax_diff=             1353
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 25    491    115    487.00 [2195]
     #big_vardiffs_with_big_inctax_diff=              376
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 26      2      0  -2900.00 [95197]
     #big_vardiffs_with_big_inctax_diff=                1
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 27    150    150     -0.01 [1761]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 28    132    132     -0.01 [36]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]=  4   2057    328   -487.00 [2195]
                      #big_inctax_diffs=             1729

taxcalc/validation> cat a14.taxdiffs
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 19    175    175     -0.01 [5713]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 22   1303      1    -25.00 [79]
     #big_vardiffs_with_big_inctax_diff=             1302
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 23      1      1      0.01 [85601]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 25    409     47    496.00 [938]
     #big_vardiffs_with_big_inctax_diff=              362
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 26      1      0   -700.00 [36539]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 27    162    162     -0.01 [737]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 28     99     99     -0.01 [5713]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]=  4   1938    274   -496.00 [938]
                      #big_inctax_diffs=             1664
```

After these two functions.py changes the tax differences are as follows:
```
taxcalc/validation> cat a13.taxdiffs
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 19    209    209     -0.01 [36]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 25    115    115      0.01 [2574]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 26      2      0  -2900.00 [95197]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 27    150    150     -0.01 [1761]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 28    132    132     -0.01 [36]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]=  4    328    328     -0.01 [2339]

taxcalc/validation> cat a14.taxdiffs
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 19    175    175     -0.01 [5713]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 22      1      1     -0.01 [85601]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 23      1      1      0.01 [85601]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 25     47     47      0.01 [89505]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 26      1      0   -700.00 [36539]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 27    162    162     -0.01 [737]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]= 28     99     99     -0.01 [5713]
TAXDIFF:col,#diffs,#1cdiffs,maxdiff[id]=  4    274    274     -0.01 [7154]
```

It is unclear what the cause of the 3 (out of 200,000) filing units having significantly different AMT taxable income (ovar[26]).  But whatever the reason, it makes no difference in any of the other intermediate tax results or in the total federal income tax liability (ovar[4]).

The taxdiffs for the other four input files (b13.in, b14.in, c13.in and c14.in) also change as a consequence of the two functions.py changes.

See commit comments for more on the two changes in functions.py logic.

### CODE REVIEW

**Comment by MattHJensen** [comment]
@GoFroggyRun, tomorrow morning, could you review the tax logic changes in functions.py.

**Comment by GoFroggyRun** [comment]
@MattHJensen OK. Will do.

**Comment by GoFroggyRun** [comment]
@martinholmer I think two changes here are definitely worthwhile. I do, however, have a couple minor concerns:
1. At the criterion where you made those units ineligible for EITC, would it be reasonable to also take care of those whose filling status is married filling separately. Please see [here](https://www.irs.gov/Credits-&-Deductions/Individuals/Earned-Income-Tax-Credit/Claiming-EITC-Without-a-Qualifying-Child) for reference.
2. Regarding the Child Tax Credit, the `+ 500` part also does not make sense to me. But according to the [Worksheet](https://www.irs.gov/pub/irs-pdf/p972.pdf) (Line 6 on Page 4), it seems that our code fails to respond to the "multiple of $1,000" requirement. So I'm wondering should we have a `math.ceil` function here to take the upper integer value? 
Please advice.

**Comment by martinholmer** [comment]
@GoFroggyRun said:
> (2) Regarding the Child Tax Credit, the + 500 part also does not make sense to me. But according to the Worksheet (Line 6 on Page 4), it seems that our code fails to respond to the "multiple of $1,000" requirement. So I'm wondering should we have a math.ceil function here to take the upper integer value? 

Sean, Thanks for your thoughtful comments on this pull request.

With regards to your question above:  Yes, you are correct about how to deal exactly correctly with the multiples-of-one-thousand language in the IRS tax form.  However, there are other places in the tax code that have similar rounding rules that the OSPC taxcalc package explicitly ignores for the sake of code simplification (the personal exemption phase-out is one example).  And this code simplification is also done in Internet TAXSIM, which is why the are no child-credit differences once the "+ 500" is dropped.

All things considered I think we should simplify the code.

In my own work I have bumped into the same issue as illustrated in the following code fragment:
```
double income_tax::
exemption_deduction_amount( const input_info& in,
                            const long filing_status,
                            const double AGI,
                            double& exemption_phase_out ) const
// returns personal exemption-deduction amount given specified info
{

  long num_exemptions = number_of_exemptions( in );
  double pre_phaseout_amt = num_exemptions * ex_amount[in.cyr]; 
  double ex_amt, phaseout_rate = ex_po_rate[in.cyr];
  if ( phaseout_rate > 0.0 ) {
    double phaseout_AGI = AGI - ex_po_lo[filing_status][in.cyr];
    if ( phaseout_AGI > 0.0 ) {
      double phaseout_unit = ex_po_unit[in.cyr];
#define TAXSIM_EXEMPTION_LOGIC
#ifdef TAXSIM_EXEMPTION_LOGIC
      double num_phaseout_units = phaseout_AGI / phaseout_unit;
        // no rounding-up as on Form 1040 in order to be consistent with TAXSIM
#else
      double num_phaseout_units = ceil( phaseout_AGI / phaseout_unit );
        // round up fractional units as on Form 1040
#endif
      double phaseout_frac = minf( 1.0, 0.02*num_phaseout_units );
      exemption_phase_out = phaseout_rate * phaseout_frac * pre_phaseout_amt;
      ex_amt = pre_phaseout_amt - exemption_phase_out;
    }
    else { // phase-out is not applied because AGI is not above lo threshold
      exemption_phase_out = 0.0;
      ex_amt = pre_phaseout_amt;
    }
  }
  else { // phase-out is not applied because phaseout_rate is zero
    exemption_phase_out = 0.0;
    ex_amt = pre_phaseout_amt;
  }
  if ( in.tracing && trace_more )
    printf( "  exemptions, exemption_phaseout, ex_amt = %ld, %.2f, %.2f\n",
            num_exemptions, exemption_phase_out, ex_amt );
  return ex_amt;
}
```

**Comment by martinholmer** [comment]
@GoFroggyRun said:
> (1) At the criterion where you made those units ineligible for EITC, would it be reasonable to also take care of those whose filling status is married filling separately? Please see [IRS webpage] for reference.

Sean, Thanks again for your helpful comments.

So you seem to be saying the nowhere else in the functions.py logic is the following rule being enforced:
```
If your filing status is married filing separately, you are ineligible to claim EITC.
```
If that is correct, then by all means, I will add that rule in the way you suggest.  So, what is the MARS value for married filing separately?  Can you confirm that this rule is not enforced elsewhere in the functions.py code?

**Comment by martinholmer** [comment]
@GoFroggyRun,  I see now that married filing separately is MARS=3.  But when I look over the code in the NumDep function (see https://github.com/OpenSourcePolicyCenter/Tax-Calculator/blob/master/taxcalc/functions.py#L1155-L1219), I have two reactions.  First, my head starts to hurt from the convoluted coding style.  But more importantly, it seems as if MARS==3 already implies a zero value for ```_preeitc```, and therefore, a zero value for ```c59660``` and ```_eitc```.  Is that how you read the code?

**Comment by feenberg** [comment]
On Wed, 14 Oct 2015, Martin Holmer wrote:

> 
> @GoFroggyRun said:
>
>       (2) Regarding the Child Tax Credit, the + 500 part also does not make sense to me. But
>       according to the Worksheet (Line 6 on Page 4), it seems that our code fails to respond to the
>       "multiple of $1,000" requirement. So I'm wondering should we have a math.ceil function here to
>       take the upper integer value?
> 
> Sean, Thanks for your thoughtful comments on this pull request.
> 
> With regards to your question above: Yes, you are correct about how to deal exactly correctly with the
> multiples-of-one-thousand language in the IRS tax form. However, there are other places in the tax code
> that have similar rounding rules that the OSPC taxcalc package explicitly ignores for the sake of code
> simplification (the personal exemption phase-out is one example). And this code simplification is also done
> in Internet TAXSIM, which is why the are no child-credit differences once the "+ 500" is dropped.

Avoiding the rounding not only simplfies the code, it avoids notches in 
the marginal rate calculation, and probably improves the accuracy of 
aggregate results.

dan

**Comment by GoFroggyRun** [comment]
> I see now that married filing separately is MARS=3. But when I look over the code in the NumDep function (see https://github.com/OpenSourcePolicyCenter/Tax-Calculator/blob/master/taxcalc/functions.py#L1155-L1219), I have two reactions. First, my head starts to hurt from the convoluted coding style. But more importantly, it seems as if MARS==3 already implies a zero value for _preeitc, and therefore, a zero value for c59660 and _eitc. Is that how you read the code?

Yes. You are right. `MARS == 3` and `MARS == 6` imply the married filing separately status, which have been already taken care of. Sorry I wasn't able to notice such implication in the first place. 
Also, thanks to your validation results against TAXISM and @feenberg 's comment, we are happy with what we have for the Child Tax Credit right now. 

This PR looks good and is ready to be merged. @MattHJensen

**Comment by MattHJensen** [comment]
Merging. Thanks @martinholmer!

**Pull request merged**
