### PR TITLE
Local change eg2

### PR DESCRIPTION
**Pull request by rkuchan**
This pull request adds an example to `docs/source/make_local_change.rst` which documents how to add a tax parameter - a floor rate for the charitable deduction - to the Tax Calculator. Included in that example are two new images that are stored in `docs/source/images` and a link to a new file that documents tax parameter nomenclature (`docs/source/parameter_taxonomy.rst`). The parameter taxonomy file relies heavily on Amy's issue: #98.

Finally, there are a couple word changes to the first example in `make_local_change.rst`.

@Amy-Xu or @MattHJensen any comments?

### CODE REVIEW

**Comment by MattHJensen** [comment]
@SherwinLott, it make make sense for you to review this as well since you have a fresh perspective on the taxcalc contributor workflow.

**Comment by Amy-Xu** [comment]
The two examples are very straightforward and clear. I really like them. I was wondering whether we need to mention the underscore issue somewhere for the adding parameter example? The parameter names have underscore at the beginning in params.json but not in functions.py. I remember I got a bit confused by the difference when I parameterized a few hard-coded values for the first time. It might be helpful to mention it?

**Comment by rkuchan** [comment]
Thank you, @Amy-Xu! I've added a note about underscores to make_local_change.rst.

**Comment by MattHJensen** [comment]
Merging! If we want to tinker we can open a new PR later.

**Pull request merged**
