### PR TITLE
Make parameters argument to @iterate_jit optional

### PR DESCRIPTION
**Pull request by talumbau**

### CODE REVIEW

**Comment by talumbau** [comment]
@MattHJensen how do I make the table to verify I didn't mess anything up on the real dataset?

**Comment by MattHJensen** [comment]
@talumbau, we set up default calculators with start_year=2013 and run calc.diagnostic_table(). We include one of these diagnostic tables from master branch and one from your topic branch.

**Comment by talumbau** [comment]
OK thanks. I will try in a little bit and post results. Assuming by tables come out correct, I intend to merge unless there are any objections.

**Comment by MattHJensen** [comment]
Looks good to me!

**Comment by talumbau** [comment]
make_params_opt_diag

The diagnostic table looks like this with master and with this change.

**Comment by talumbau** [comment]
Seems like everything is good to go. Will merge soon.

**Pull request merged**
