### PR TITLE
move default_data and related to ParametersBase

### PR DESCRIPTION
**Pull request by talumbau**
- make ParametersBase abstract base class
- test that Growth and Behavior now also support default_data

### CODE REVIEW

**Comment by talumbau** [comment]
marking this as WIP because additional changes might be needed for webapp.

**Comment by MattHJensen** [comment]
@talumbau said: 

>I will need to merge  PR #393: [WIP] move default_data and related to ParametersBase by talumbau in OpenSourcePolicyCenter/Tax-Calculator on GitHub before I can do the version bump, so any review here would be helpful

cc @Amy-Xu, @martinholmer

**Comment by MattHJensen** [comment]
:+1: from me.

**Comment by MattHJensen** [comment]
@talumbau, I'd say go ahead and merge this when it starts blocking you.

**Pull request merged**
