### PR TITLE
refactor duplicate code to base class; rename params.json

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
This PR implements the cleanup of duplicate behavior and parameters code, as discussed in part on #367.  

I moved the set_year, _update and properties of the Behavior/Parameters class to ParametersBase.  I moved params.json to current_law_policy.json.  We may want to consider now naming Parameters to Policy.

In the comments on #367, I mentioned that providing standalone functions would be better than a base class, but I found writing the base class made more sense because most of the methods I was writing took a Behavior/Parameters object as the first argument.

### CODE REVIEW

**Comment by PeterDSteinberg** [comment]
I forgot to pep8 check locally.  I'll do that now.

**Comment by MattHJensen** [comment]
Very nice @PeterDSteinberg. I'll dig into this some more over the weekend. Also cc @martinholmer for review when he is back next week. 

>We may want to consider now naming Parameters to Policy.

I'm :+1: on this

**Comment by PeterDSteinberg** [comment]
The latest 2 commits change Parameters to Policy, calculator_object._params to calculator_object._policy, params to policy throughout the code.  I updated the Behavioral_Example ipython notebook but not 10_minutes_to_TaxCalc ipython notebook.

**Comment by martinholmer** [comment]
@PeterDSteinberg,
Pull request #371 is a very positive development.  I like, in particular, the fact that you went beyond my suggestion (to put common parameter-related code in utils.py) to derive Policy, Behavior, etc., from a base parameters class.  Do you want to consider moving the expand utilities from utils.py to ParametersBase?  That would locate all the common time-series parameter code in one place.  Or is there some reason to keep the expand utilities in the utils.py file?

cc @MattHJensen

**Comment by PeterDSteinberg** [comment]
I agree @martinholmer  it makes sense to put a lot of the utils.py code into the base class.  I'll work on that tonight and push changes.  cc @MattHJensen

**Comment by PeterDSteinberg** [comment]
Failed due to pep8.  I can fix that tomorrow if no one gets to it today.

**Comment by MattHJensen** [comment]
just opened this one https://github.com/PeterDSteinberg/Tax-Calculator/pull/2

**Comment by MattHJensen** [comment]
@martinholmer, could you review this PR? It would be best if this were committed quickly if possible so @amy-xu can proceed with #368. Also, this PR will probably be difficult to maintain if it is left outstanding since it touches so many parts of the codebase.

**Comment by martinholmer** [comment]
@PeterDSteinberg,  You may need to merge in the latest changes on master branch.
cc @MattHJensen

**Comment by MattHJensen** [comment]
@martinholmer, I think there are just pep8 fixes outstanding, which are resolved with PeterDSteinberg#2. What do you think of the content of this PR, current test-failure aside?

**Comment by martinholmer** [comment]
@MattHJensen,  I didn't see any problems in a quick review.  If there are problems, we can fix later.  This is an enormous improvement, so we should get it into master as soon as possible.  I would merge into master, but can see your elimination of pep8 warnings.  cc @PeterDSteinberg

**Comment by martinholmer** [comment]
@MattHJensen,  Can you merge in your pep8 fixes to this PR so that it passes the travis check-in tests, and then I'll be happy to merge it into the master branch.  I want to do this __before__ the merge of the SimpleTaxIO class, so that this PR does not become stale.  When do you think you can merge your pep8 fixes into this PR?

**Comment by MattHJensen** [comment]
@martinholmer, I have a PR open to @PeterDSteinberg's fork with the pep8 fixes. He needs to merge that, which will include those commits in this PR; and I believe he will do that today. If there is a reason to get this merged sooner, I could open a new PR to ospc/master with all of Peter's commits as well as the pep8 fixes, but that PR would supplant this PR.

**Comment by martinholmer** [comment]
@MattHJensen said:
> I have a PR open to @PeterDSteinberg's fork with the pep8 fixes. He needs to merge that, which will include those commits in this PR; I believe he will do that today. If there is a reason to get this merged sooner, I could open a new PR to ospc/master with all of Peter's commits as well as the pep8 fixes, but that PR would supplant this PR.

OK, let's wait for Peter to do that later today.

**Comment by MattHJensen** [comment]
Thanks @PeterDSteinberg! Merging. 

cc @martinholmer @amy-xu

**Pull request merged**
