### PR TITLE
fix expand_1D to match convention of expand_2D

### PR DESCRIPTION
**Pull request by talumbau**
- producing new array of n values requires only n-1 inflation rates

### CODE REVIEW

**Comment by martinholmer** [comment]
**Don't you dare commit this!**  This will break substantial parts of pull request #321.
A better approach is to commit pull request #321 and then figure out how CBO
applies inflation rates, which is something @MattHJensen is going to do.  Once,
we know what CBO does with its inflation rates we will be able to make a sensible
decision about how to do this in the OSPC Tax-Calculator.

**Comment by MattHJensen** [comment]
@martinholmer, it seems like T.J. gave you a scare! But don’t worry about anything ever getting merged before a relevant issue (in this case #325) has been fully discussed — we have done a very good job as a community at upholding this principle. (And I should probably add something on this to our contributor docs). That said, it is certainly possible to make mistakes or for someone not to notice that an issue is relevant, so it is very helpful for you to note that this PR depends on the discussion in #325, especially since it wasn’t marked as such already. 

I’ll follow up over at #325 on how CBO reports inflation numbers shortly

**Comment by talumbau** [comment]
I opened #326 as part of a discussion of #325 . If we decide the fix should be different after Matt’s followup, then I would still advocate for having a separate PR that only implements the fix. My intent was never to merge my fix with no discussion.

The reason for having a fix-specific PR, more generally, is that it fits into a workflow for handling a bug that tends to be very successful on github:

- Create an issue that describes the bug as succinctly as possible, preferably with some small code example
- If possible, create a PR that resolves that bug (and only that bug) in as few lines as is reasonably possible. Then invite feedback on your solution.

There are many reasons why this is a good way to resolve a bug. Some of them are:

- It allows others to minimize the time they need to spend to come up to speed on the particular issue. If they can read a few lines of code/text that describe the problem, and then a few lines of code that fix the problem, it’s much more efficient than reading a large PR that has other items inside it.
- It invites the maximum possible scrutiny to the community to discuss the issue. The issue is labeled as a bug, and interested parties can now comment in one place on this particular issue. The discussion can range from possible solutions, to addressing whether or not the behavior is actually a bug (not relevant in this case, but often that does come up!)
- It provides a clean history of the issue. If a PR is labeled as ‘Fix for #325’ or something similar, it’s easy to look through the history of the repository and see how the bug got fixed.

#321 on the other hand is a very large PR and needs additional review. There are many diffs of the form
```
-           with open(file_name) as f:
-               params = json.loads(f.read())
+          with open(file_name) as pfile:
+              params = json.loads(pfile.read())
```
which one has to look through, which are more formatting/style changes rather than substantive changes. Typically, one would have a separate style/formatting PR. For the parts that I have looked at, I haven’t had a chance to put my comments/questions in. There are likely good reasons for the choices made, but I haven’t had time to consider them yet.

**Comment by martinholmer** [comment]
If the project team decides to change it prior inflation-indexing scheme, then it would be less
work to commit pull request #321 before making the change to a new inflation-indexing scheme.
Remember pull request #321 found another bug as well, which has not been discussed in its
own issue as has the inflation-indexing bug.

**Comment by martinholmer** [comment]
I suggest that if everybody is OK with pull request #326, then we should proceed
as follows: (1) commit #326 to master, (2) I will fix the test results in pull request #321
to agree with the new method of applying inflation rates, and (3) commit #321 to master.

Does this seem like a reasonable approach? If not, what would be a better approach?

**Comment by talumbau** [comment]
I think that is the right flow, with one or two small additional details. I will post a PR with an additional test that reveals a particular issue with how `dropq` uses `taxcalc`. If I am correct, once you merge in that change with the `parameters-edit2` branch, you will see a test failure. In my testing, this actually reveals a bug in a different place and not in the code in `parameters-edit2` branch. Anyway, details to come. I think a good first step though is the merge of this PR, and then merging master in to your branch.

**Comment by martinholmer** [comment]
TJ @talumbau, Just go ahead and commit pull request #326 and then
I'll fix up pull request #321.  Isn't that the easiest way to proceed?
@MattHJensen, do you see any problems with that workflow?

**Comment by MattHJensen** [comment]
Sounds like we're all in agreement on merging #326 -- It might make sense to wait on fixing up #321 until TJ has had a chance to open the test PR in case that will affect how you should fix #321, but we'll know better whether that is the case once T.J. has a chance to post the forthcoming details on that. @talumbau, just because I'm am only 98% certain that your forthcoming test PR doesn't have anything to do with merging #326, I'll let you go ahead and make this merge.

**Pull request merged**
