### PR TITLE
Parameterize hard-coded values and rename all params for consistency

### PR DESCRIPTION
**Pull request by Amy-Xu**
I made several changes on this branch. First, I added the hard-coded values that are going to show up on the webpage to our params.json file. Second, I included hair cut parameters for a few e-codes representing adjustments. These variables are all in function Adj(). Third, I renamed the parameters with the naming convention proposed in #98 and switched all names in both params.json and function.py. To run py.test, I also changed a few lines in test_calculate.py to match with this set of new param names.

### CODE REVIEW

**Comment by MattHJensen** [comment]
@Amy-Xu could you compare results.csv from this branch to results.csv from master? If the two are the same then I will merge.

**Comment by MattHJensen** [comment]
If you load them both as dataframes, you can run: assert_frame_equal(df1, df2)

**Comment by Amy-Xu** [comment]
should be good right now

**Comment by MattHJensen** [comment]
Why is AMT exemption phaseout start "_AMT_em_ps" but Child Tax Credit Phaseout Start is "_CTC_pe"? In particular, why are the last letters different?

**Comment by Amy-Xu** [comment]
...........I think that's a typo...............let me fix it........
Is there anything else weird you noticed?

**Comment by MattHJensen** [comment]
Looks good now. Merging.

**Pull request merged**
